# Generated by Django 3.1.7 on 2021-04-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funcao',
            field=models.ManyToManyField(to='ministerio.Funcao'),
        ),
    ]
