# Generated by Django 3.1.7 on 2021-04-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name_plural': 'Funcoes'},
        ),
        migrations.AlterModelOptions(
            name='ministerio',
            options={'verbose_name_plural': 'Ministerios'},
        ),
    ]
