# Generated by Django 3.1.7 on 2021-04-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='funcao',
        ),
        migrations.AddField(
            model_name='evento',
            name='observacao',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='escala',
            name='evento',
        ),
        migrations.AddField(
            model_name='escala',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='escala.evento', verbose_name='Evento'),
            preserve_default=False,
        ),
    ]
